version: '3.4'

services:
  app:
    image: sprutdobro/excursions:latest
    environment:
      - NODE_ENV=production
      - PROD_DB_STRING=${PROD_DB_STRING}
      - PROD_DB_USER=${PROD_DB_USER}
      - PROD_DB_PWD=${PROD_DB_PWD}
      - SESSION_SECRET=${SESSION_SECRET}
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    ports:
      - 80:3000
    volumes:
      - ./.env:/usr/src/app/.env
      - ./id_rsa_priv.pem:/usr/src/app/id_rsa_priv.pem
      - ./id_rsa_pub.pem:/usr/src/app/id_rsa_pub.pem
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - ./mgob/storage:/storage
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mgob:
    image: stefanprodan/mgob:latest
    ports:
      - 8095:8090
    volumes:
      - ./mgob/config:/config
      - ./mgob/storage:/storage
      - ./mgob/tmp:/tmp
      - ./mgob/data:/data
volumes:
  data:
