version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app
    links: 
      - mongodb
  mongodb:
    image: mongo:latest
    command: [--auth]
    ports: 
      - 27017:27017
    volumes: 
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789

volumes: 
  data: