version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PROD_DB_STRING=${PROD_DB_STRING}
      - PROD_DB_USER=${PROD_DB_USER}
      - PROD_DB_PWD=${PROD_DB_PWD}
      - SESSION_SECRET=${SESSION_SECRET}
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app:z
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  mgob:
    image: stefanprodan/mgob:latest
    ports:
      - 8090:8090
    volumes:
      - ./mgob/config:/config
      - ./mgob/storage:/storage
      - ./mgob/tmp:/tmp
      - ./mgob/data:/data
volumes:
  data:
